---
  # should put a condition around this for centos only
  - name: Installs epel repo so we can add NGINX
    yum:
      name: epel-release
      state: latest

  - name: Installs nginx web server
    yum:
      name: nginx
      state: latest

  - name: Ensure that nginx user is locked down
    user:
      name: nginx
      shell: /sbin/nologin
      comment: "Nginx web server"
      uid: 995
      group: nginx
      # groups: web

  - name: Changes permissions to web folder
    file:
      path: /var/www
      owner: root
      group: root
      mode: 0755
      recurse: yes

  - name: Setup NGINX config
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0444
    notify: reload nginx

  - name: make sure nginx is enabled and started
    service:
      name: nginx
      enabled: yes
      state: started

  - name: Copy Selinux Template .te
    template:
      src: mysemanage.te
      dest: /root/mysemanage.te
      owner: root
      group: root
      mode: 0400

  - name: Update selinux poilicy to allow nginx to proxy to localhost:9292 for sinatra based on above .te file
    shell: |
      checkmodule -M -m -o mysemanage.mod mysemanage.te
      semodule_package -o mysemanage.pp -m mysemanage.mod
      semodule -i /root/mysemanage.pp
      EXCODE=$?
      if [ "${EXCODE}" = "0" ]; then
        echo ${EXCODE} > /root/selinux.done
      fi
      exit ${EXCODE}
    args:
        chdir: /root
        executable: /bin/bash
        creates: /root/selinux.done
