---
  - name: clones git repo
    git:
      repo: https://github.com/rea-cruitment/simple-sinatra-app.git
      dest: "{{ www_dir }}/{{ sinatra_dir }}"
      force: yes

  - name: installs required gems
    command: "/bin/scl enable rh-ruby22 'bundle install --binstubs=../{{ bundle_dir }} --path=../{{ gem_dir }}'"
    args:
        chdir: "{{ www_dir }}/{{ sinatra_dir }}"
        creates: "{{ www_dir }}/{{ bundle_dir }}"

  - name: create sinatra group
    group:
      name: "{{ sinatra_user }}"
      gid: "{{ sinatra_uid }}"
      state: present

  - name: create user for sinatra
    user:
      name: "{{ sinatra_user }}"
      shell: /sbin/nologin
      comment: "Sinatra Server"
      group: "{{ sinatra_user }}"
      uid: "{{ sinatra_uid }}"

  - name: setup rackup startup script
    template:
      src: rackup.bash
      dest: /usr/sbin/rackup.bash
      owner: root
      group: root
      mode: 0755
    notify: restart sinatra.service

  - name: setup sinatra service in systemd
    template:
      src: sinatra.service
      dest: /usr/lib/systemd/system/sinatra.service
      owner: root
      group: root
      mode: 0644
    notify: daemon-reload

  - name: enable sinatra service
    systemd:
      name: sinatra.service
      enabled: yes
      state: started
